import { createReadStream } from "node:fs";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { config } from "../config/index.js";

// Local-disk object store. Same interface can be backed by S3 later.
const root = path.resolve(config.UPLOAD_DIR);
await mkdir(root, { recursive: true, mode: 0o700 });

// keys are generated by us (uuid.ext); anything else is refused, so no path traversal
function resolveKey(key) {
  if (!/^[\w-]+\.[a-z0-9]+$/.test(key)) throw new Error("invalid storage key");
  return path.join(root, key);
}

export const putObject = (key, data) => writeFile(resolveKey(key), data, { flag: "wx", mode: 0o600 });
export const getObject = (key) => readFile(resolveKey(key));
export const readObjectStream = (key) => createReadStream(resolveKey(key));
export const deleteObject = (key) => rm(resolveKey(key), { force: true });
